# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "betauseraccess"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Your Name"]
  s.date = "2012-06-05"
  s.email = "you@email.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "app/controllers/betauseraccess/sign_up_for_beta_accesses_controller.rb",
    "app/helpers/application_helper.rb",
    "app/helpers/betauseraccess/widgets_helper.rb",
    "app/models/betauseraccess/sign_up_for_beta_access.rb",
    "app/views/betauseraccess/sign_up_for_beta_accesses/_form.html.erb",
    "app/views/betauseraccess/sign_up_for_beta_accesses/edit.html.erb",
    "app/views/betauseraccess/sign_up_for_beta_accesses/index.html.erb",
    "app/views/betauseraccess/sign_up_for_beta_accesses/new.html.erb",
    "app/views/betauseraccess/sign_up_for_beta_accesses/show.html.erb",
    "app/views/betauseraccess/sign_up_for_beta_accesses/thanks.html.erb",
    "app/views/layouts/betauseraccess.html.erb",
    "config/routes.rb",
    "lib/acts_as_widget/base.rb",
    "lib/application_controller.rb",
    "lib/application_helper.rb",
    "lib/betauseraccess.rb",
    "lib/engine.rb",
    "lib/rails/generators/betauseraccess/betauseraccess_generator.rb",
    "lib/rails/generators/betauseraccess/templates/initializer.rb",
    "lib/rails/generators/betauseraccess/templates/migration.rb",
    "lib/rails/generators/betauseraccess/templates/schema.rb",
    "lib/rails/railties/tasks.rake",
    "public/images/betauseraccess.jpg",
    "public/stylesheets/betauseraccess.css"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Description of your gem"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

